dependencies:
  - json
  - re
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - sklearn
  - tree
  - accuracy_score
  - confusion_matrix
  - graphviz
  - export_graphviz
  - scipy
  - collections
  - ipykernel
  - bokeh
  - counter
  - random
  - itertools
